import { doc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../config/firebase';

export const INITIAL_KB_CONTENT: Array<{
  id: string;
  url: string;
  title: string;
  content: string;
  tokens: string[];
}> = [
  { id: 'home', url: '/', title: 'Home - Wasilah', content: 'Wasilah is a community service organization dedicated to creating positive change through education, healthcare, environmental initiatives, and community development projects. We believe in empowering communities and creating sustainable impact through volunteer-driven programs. Our mission is to connect people who want to make a difference with opportunities that create lasting change.', tokens: ['wasilah','community','service','organization','education','healthcare','environmental','initiatives','development','projects','empowering','communities','sustainable','impact','volunteer','programs','mission','connect','people','difference','opportunities','change'] },
  { id: 'about', url: '/about', title: 'About Us - Wasilah', content: 'Wasilah was founded with a vision to bridge communities and create meaningful impact through collaborative service. We work across multiple sectors including education, healthcare, environmental conservation, and community development. Our team comprises dedicated volunteers, community leaders, and professionals who share a common goal: creating sustainable positive change in communities across Pakistan. We operate with transparency, accountability, and a deep commitment to serving those in need.', tokens: ['wasilah','founded','vision','bridge','communities','meaningful','impact','collaborative','service','sectors','education','healthcare','environmental','conservation','community','development','team','volunteers','leaders','professionals','goal','sustainable','change','pakistan','transparency','accountability','commitment','serving'] },
  { id: 'projects', url: '/projects', title: 'Projects - Wasilah', content: 'Our projects span multiple areas of community impact. Education Programs: We provide tutoring, scholarship support, and educational resources to underprivileged students. Healthcare Initiatives: Free medical camps, health awareness campaigns, and preventive care programs. Environmental Conservation: Tree planting drives, beach cleanups, and sustainability workshops. Community Development: Infrastructure projects, skills training, and livelihood support programs. Each project is designed with community input and measured for sustainable impact.', tokens: ['projects','community','impact','education','programs','tutoring','scholarship','support','resources','students','healthcare','initiatives','medical','camps','health','awareness','campaigns','preventive','care','environmental','conservation','tree','planting','beach','cleanups','sustainability','workshops','development','infrastructure','skills','training','livelihood','designed','measured','sustainable'] },
  { id: 'volunteer', url: '/volunteer', title: 'Volunteer - Wasilah', content: 'Join us as a volunteer and make a real difference in your community. We welcome volunteers aged 16 and above (parental consent required for minors). No prior experience necessary - we provide orientation and training. Volunteer opportunities include: event coordination, tutoring, healthcare support, environmental activities, administrative help, and social media management. You can volunteer once a month or multiple times per week based on your availability. After 20 hours of service, you will receive a volunteer certificate. Apply through our volunteer form and we will contact you within 3-5 business days.', tokens: ['volunteer','join','difference','community','welcome','aged','experience','orientation','training','opportunities','event','coordination','tutoring','healthcare','support','environmental','activities','administrative','social','media','management','availability','hours','service','certificate','apply','form','contact','business','days'] },
  { id: 'events', url: '/events', title: 'Events - Wasilah', content: 'We organize regular community events to engage volunteers and create impact. Upcoming events include health fairs with free medical checkups, educational workshops for skills development, tree planting drives for environmental conservation, and community gatherings for cultural exchange. Most events are free to attend and open to the public. Check our events calendar for schedules and registration details. We typically host 2-3 events per month across Karachi, Lahore, and Islamabad. Follow us on social media for event updates and photos.', tokens: ['events','organize','community','engage','volunteers','impact','health','fairs','medical','checkups','educational','workshops','skills','development','tree','planting','environmental','conservation','gatherings','cultural','exchange','free','attend','public','calendar','schedules','registration','details','month','karachi','lahore','islamabad','social','media','updates','photos'] },
  { id: 'contact', url: '/contact', title: 'Contact - Wasilah', content: 'Get in touch with us! We have offices in three major cities. Karachi Office: Main Office Complex, Clifton Block 5. Lahore Office: Model Town Extension. Islamabad Office: Blue Area Sector F-6. Email: info@wasilah.org. You can also reach us through this chat widget for quick questions. Our team responds to emails within 24 hours during business days. Follow us on Facebook, Instagram, and Twitter for updates and stories.', tokens: ['contact','touch','offices','cities','karachi','office','complex','clifton','lahore','model','town','islamabad','blue','area','sector','email','info','wasilah','reach','chat','widget','questions','team','responds','hours','business','days','facebook','instagram','twitter','updates','stories'] }
];

export async function seedKnowledgeBase() {
  const results: { success: string[]; failed: Array<{ title: string; error: string }> } = { success: [], failed: [] };
  for (const page of INITIAL_KB_CONTENT) {
    try {
      const docRef = doc(db, 'kb', 'pages', 'content', page.id);
      await setDoc(docRef, { ...page, lastUpdated: serverTimestamp(), source: 'admin-enable' });
      results.success.push(page.title);
    } catch (e: any) {
      results.failed.push({ title: page.title, error: e?.message || 'unknown error' });
    }
  }
  return results;
}
